services:
    reservations: 
        build:
            context: .
            dockerfile: ./app/reservations/dockerfile
            target: development
        command: pnpm run start:dev reservations
        ports:
        - '3000:3000'
        volumes:
        - .:/usr/src/app
    mongo:
        image: mongo